# (term, source) -- SUG=get_keyword_suggestions(app 6758740138, store) 2026-09-28; EXT=extract_competitors_keywords(seed) 2026-09-28;
# COMP=competitor name/subtitle n-gram from serp_2026-09-28.json / competitors.md; NAT=natural-query pattern of the locale
FR = [
("puzzle alarm clock","SUG fr: suggestion 'puzzle alarm clock' (pop20)"),
("puzzle alarm","SUG fr: suggestion 'puzzle alarm'"),
("math alarm clock","SUG fr: suggestion 'math alarm clock' (pop31); COMP 'Mathe Alarm Clock - Réveil'"),
("sunrise app","SUG fr: suggestion 'sunrise app'"),
("my sunrise","SUG fr: suggestion 'my sunrise'"),
("wake up","SUG fr: suggestion 'wake up'; EXT fr seed \"simulateur d'aube\""),
("réveil musique","EXT fr: token 'musique'(75) seeds alarme/réveil maths/réveil intelligent; COMP 'Réveil Musique et Radio','Reveil: Alarme Clock | Réveil Musique'"),
("réveil radio","EXT fr: token 'radio'(66) seeds alarme/réveil maths; COMP 'Radio Réveil : Horloge, Météo'"),
("radio réveil","COMP fr: 'Radio Réveil : Horloge, Météo' / 'iReveil – Radio Réveil Premium'"),
("alarme musique","EXT fr: token 'musique' seed alarme; COMP subtitle 'Alarme Reveil Musique'"),
("alarme horloge","EXT fr: token 'horloge'(70) seed alarme; COMP subtitle 'Matin Alarme Horloge'"),
("alarme minuteur","EXT fr: token 'minuteur' seed alarme; COMP 'Alarme & Minuteur'"),
("réveil ia","EXT fr: token 'ia'(73) seed réveil intelligent"),
("réveil debout","EXT fr: token 'debout' seeds anti snooze/réveil mission"),
("réveil snooze","EXT fr: token 'snooze'(30) seeds réveil gros dormeur/réveil mission"),
("alarme snooze","EXT fr: token 'snooze'; COMP subtitle 'Horloge, sommeil, nuit, snooze'"),
("sunrise simulator","EXT fr: token 'simulator'(64) seed 'sunrise alarm clock'"),
("suivi cycle","EXT fr: combo 'suivi cycle' seeds alarme/simulateur d'aube/sunrise alarm clock"),
("tracker sommeil","EXT fr: combo 'tracker sommeil' seeds anti snooze/simulateur d'aube"),
("analyse sommeil","EXT fr: combo 'analyse sommeil' seed réveil intelligent"),
("tracker de sommeil","COMP fr: 'ShutEye: Tracker de sommeil','Pillow. Tracker de sommeil'"),
("suivi de sommeil","COMP fr: 'Sleep Cycle - Suivi de Sommeil'"),
("suivi du ronflement","COMP fr: Alarmy subtitle 'Étude & Suivi du ronflement'"),
("réveil pour moi","COMP fr: 'Réveil pour moi.' (Mosaic, SERP réveil #3)"),
("réveil avec défis","COMP fr: 'WakeBolt: Réveil avec Défis'"),
("réveil à défis","COMP fr: 'Wakup!: Réveil à Défis'"),
("réveil défi","NAT fr: 'réveil <feature>' singular of 'réveil défis'"),
("alarme défi","NAT fr: 'alarme <feature>'"),
("alarme avec mission","NAT fr: 'alarme avec X' (COMP 'Wayk: Réveil avec Mission')"),
("alarme missions","COMP fr: 'Alarme : Réveil calcul & scan | Missions pour bien se lever'"),
("réveil anti snooze","COMP fr: 'Hibern' subtitle 'Réveil anti-snooze', 'Up: Réveil anti-snooze'"),
("anti-snooze","COMP fr: WakeBolt subtitle 'Anti-snooze pour gros dormeurs' (hyphen variant)"),
("stop snooze","COMP fr: Wayk subtitle 'Stop snooze, levez-vous tôt'"),
("réveil anti-sommeil","COMP fr: 'À l'heure' subtitle 'Réveil matin anti-sommeil'"),
("sans répétition","COMP fr: Risen subtitle 'Sans répétition. Gros dormeurs'"),
("réveil sans répétition","NAT fr: 'réveil sans X' (COMP Risen/Wakup 'Fini la Répétition')"),
("gros dormeurs","COMP fr: Risen 'Gros dormeurs', WakeBolt 'pour gros dormeurs'"),
("réveil pour gros dormeur","NAT fr: 'réveil pour <user>'"),
("alarme gros dormeur","NAT fr: 'alarme <user>' (COMP 'Rooster : réveil gros dormeur')"),
("réveil pour sommeil lourd","NAT fr: 'réveil pour <problème>'"),
("sommeil profond","NAT fr: synonym of sommeil lourd"),
("réveil sommeil profond","NAT fr: 'réveil <problème>' synonym"),
("alarmes fortes","COMP fr: 'Réveil : Alarmes Fortes ◎'"),
("réveil alarme forte","COMP fr: Rooster subtitle 'Alarme forte qui te fait lever' + réveil"),
("réveil pour se lever","COMP fr: 'Ryse - Réveil pour se lever'"),
("bien se lever","COMP fr: subtitle 'Missions pour bien se lever'"),
("se lever le matin","NAT fr: 'se lever le matin'"),
("se réveiller le matin","NAT fr: 'se réveiller le matin'"),
("se réveiller tôt","NAT fr: 'se réveiller tôt'"),
("réveille-toi","COMP fr: 'Hibern: Réveille-toi.Prouve-le'"),
("réveille matin","NAT fr: no-hyphen spelling of 'réveille-matin' (tracked)"),
("réveil du matin","COMP fr: 'Réveil intelligent du matin'"),
("réveil matin gratuit","NAT fr: 'X gratuit'"),
("alarme calcul","COMP fr: 'Alarme : Réveil calcul & scan'"),
("calcul mental","NAT fr: feature term (réveil calcul mental tracked)"),
("alarme mathématique","NAT fr: 'alarme <feature>' (EXT token 'mathematique' 50)"),
("réveil tout doux","COMP fr: 'PureWake - Réveil Tout Doux'"),
("alarme douce","NAT fr: 'alarme <attribut>' (doux core)"),
("alarme progressive","NAT fr: 'alarme <attribut>' (progressif core)"),
("sonnerie douce","NAT fr: 'sonnerie <attribut>'"),
("se réveiller en douceur","NAT fr: verb form of 'réveil en douceur' (COMP Sleepwave 'Réveil en douceur')"),
("réveil naturel doux","COMP fr: 'Réveil Doux - Wake Up Beauty | Réveil Naturel'"),
("lever du soleil","NAT fr: core 'lever du soleil' alone (COMP 'Lever du soleil tous les jours')"),
("simulateur lever de soleil","NAT fr: 'simulateur de X' (COMP 'Simulateur d'aube')"),
("réveil lumière du jour","COMP fr: Zenrise 'Réveil Soleil | Lumière du jour'"),
("réveil lumière naturelle","NAT fr: 'réveil lumière <attribut>'"),
("lumière réveil","NAT fr: word-order variant of 'réveil lumière'"),
("lampe réveil","NAT fr: 'lampe réveil' (light-alarm intent)"),
("aurore","COMP fr: Glow Alarm 'Réveil aurore'"),
("sonnerie alarme","NAT fr: 'sonnerie X'"),
("sonnerie de réveil","COMP fr: RingTune 'Sonnerie et musique de réveil'"),
("musique de réveil","COMP fr: RingTune 'Sonnerie et musique de réveil'"),
("phase de sommeil","NAT fr: smart-wake feature term"),
("réveil phase sommeil léger","NAT fr: 'réveil <feature>'"),
("réveil cycle sommeil","NAT fr: 'réveil + cycle sommeil' (EXT combo 'cycle sommeil')"),
("alarm clock for heavy sleepers","NAT fr: English query in FR store (en-GB fields)"),
("loud alarm clock","NAT fr: English query in FR store (SUG de 'loud alarm clock' pop40)"),
("heavy sleeper alarm","NAT fr: English query in FR store"),
("mission alarm","NAT fr: English query in FR store"),
("gentle alarm","NAT fr: English query in FR store (en-GB 'gentle')"),
("sunrise lamp","NAT fr: English query in FR store (en-GB 'sun','lamp')"),
("wake up alarm","NAT fr: English query in FR store"),
]
DE = [
("waking up","SUG de: suggestion 'waking up' (pop40); EXT seed 'wecker mit aufgaben'"),
("puzzle alarm","SUG de: suggestion 'puzzle alarm'"),
("puzzle alarm clock","SUG de: suggestion 'puzzle alarm clock'"),
("math alarm clock","SUG de: suggestion 'math alarm clock' (pop31)"),
("miracle morning","SUG de: suggestion 'miracle morning'"),
("radiowecker","SUG de: suggestion 'radiowecker' (pop20); COMP 'Wecker HD' subtitle 'Radiowecker mit musik töne'"),
("morgen","SUG de: suggestion 'morgen'; EXT seed 'sunrise alarm clock' (live keyword token)"),
("wake up","SUG de: suggestion 'wake up'; EXT seeds lichtwecker/sonnenaufgang wecker"),
("wecker iphone kostenlos","SUG de: suggestion 'wecker iphone kostenlos' (pop55)"),
("wecker mit spotify","SUG de: suggestion 'wecker mit spotify'"),
("bewegungs wecker","SUG de: suggestion 'bewegungs wecker'; COMP 'Bewegungs Wecker' (SERP wecker #3)"),
("snooze","SUG de: suggestion 'snooze' (pop30); EXT token seeds mission wecker/wecker laut/..."),
("wecker iphone","SUG de: suggestion 'wecker iphone'"),
("loud alarm clock","SUG de: suggestion 'loud alarm clock' (pop40)"),
("wecker extrem","SUG de: suggestion 'wecker extrem'"),
("wake","SUG de: suggestion 'wake'"),
("wecker app","EXT de: combo 'wecker app'(54) seeds mission wecker/sonnenaufgang wecker/sunrise alarm clock/wecker"),
("uhr wecker","EXT de: combo 'uhr wecker'(50) seeds sanft aufwachen/wecker laut; COMP subtitle 'uhr mit sekunden & uhr wecker'"),
("wecker musik","EXT de: combo 'wecker musik' seeds mathe wecker/sanft aufwachen/wecker/wecker mit aufgaben"),
("barcode wecker","EXT de: combo 'barcode wecker' seeds wecker mit aufgaben/wecker ohne schlummern; COMP 'Barcode Wecker'"),
("spotify wecker","EXT de: combo 'spotify wecker' seeds wecker/wecker mit aufgaben"),
("clock alarm","EXT de: combo 'clock alarm' seeds mathe wecker/wecker/..."),
("led wecker","EXT de: token 'led'(54) seed wecker laut; COMP 'Digital uhr - LED Wecker'"),
("wecker timer","EXT de: token 'timer'(60) seeds mathe wecker/wecker; COMP 'Wecker & Timer'"),
("wecker uhr","EXT de: token 'uhr'(68) seeds wecker/mathe wecker/...; COMP 'Wakeify: Musik-Wecker & Uhr'"),
("nfc wecker","EXT de: token 'nfc'(57) seed wecker ohne schlummern; COMP OkiPaca 'NFC & QR gegen Verschlafen'"),
("qr wecker","COMP de: 'WakeProof: QR Wecker'"),
("wecker foto","EXT de: token 'foto'(62) seed mission wecker; COMP Aufwachalarm 'Foto-Mission, kein Snooze'"),
("wecker für mich","COMP de: 'Wecker für mich.' (Mosaic, SERP wecker #5)"),
("wecker hd","COMP de: 'Wecker HD - Alarm Clock' (SERP wecker #10)"),
("wecker mit musik","COMP de: 'Wecker mit Musik - Aufwachen', 'Wecker app mit Musik'"),
("musik wecker","COMP de: 'Musik Wecker', 'Musik uhr wecker'"),
("wecker kostenlos","NAT de: 'X kostenlos'"),
("wecker ohne werbung","NAT de: 'X ohne Werbung' (COMP 'Uhr - Keine Werbung')"),
("tiefschläfer-wecker","COMP de: 'Rooster: Tiefschläfer-Wecker', 'Hypnos: Tiefschläfer-Wecker'"),
("alarm für tiefschläfer","COMP de: 'Wecker - Wecker zum Aufwachen | Alarm für Tiefschläfer'"),
("lauter wecker für tiefschläfer","COMP de: subtitles 'Lauter Wecker für Tiefschläfer' (Roomwake, Wecker mit Aufgaben & Mathe)"),
("laute alarme für tiefschläfer","COMP de: 'Wecker: Laute Alarme ◎' subtitle"),
("wecker für schlafmützen","NAT de: colloquial user synonym of Tiefschläfer"),
("wecker missionen","COMP de: 'WonUp: Wecker & Missionen','BedOut - Wecker & Missionen','Wakezilla'"),
("aufwachmissionen","COMP de: 'Wake Boom' subtitle 'Wecker mit Aufwachmissionen'; 'Aufwach-Missionen'"),
("weck aufgaben","COMP de: 'Alarmly - Weck-Aufgaben'"),
("mathe aufgaben wecker","NAT de: word-order variant of 'wecker mathe aufgaben'"),
("wecker mit mathe","NAT de: 'wecker mit X' (COMP 'Wecker mit Aufgaben & Mathe')"),
("mathe alarm","COMP de: 'Math Alarm - Mathe Wecker'; SUG us 'mathe alarm' (iter-01)"),
("mein mathe wecker","COMP de: 'Mein Mathe Wecker' (SERP wecker aufgaben)"),
("rätsel wecker","COMP de: 'Wakup!: Rätsel Wecker'"),
("kopfrechnen wecker","NAT de: 'X wecker' with mental-math synonym"),
("ohne snooze","COMP de: WonUp 'Ohne Snooze', Hypnos 'Ohne Snooze.'"),
("kein snooze","COMP de: Rizen/FitAlarm/Wakey/Wakr 'kein Snooze'"),
("wecker kein snooze","NAT de: 'wecker + kein snooze'"),
("wecker ohne schlummerfunktion","COMP de: Roosta subtitle 'Wecker ohne Schlummerfunktion'"),
("schlummerfunktion","COMP de: Roosta 'Schlummerfunktion'"),
("ohne schlummern","COMP de: 'Waiki: Wecker ohne Schlummern'"),
("wecker gegen verschlafen","COMP de: 'Alarme: Mathe & Scan Wecker | Aufgaben gegen Verschlafen' + wecker"),
("besser aufwachen","NAT de: 'besser X' (COMP bedr 'Morgens besser wach werden!')"),
("leichter aufwachen","NAT de: 'leichter X'"),
("früh aufwachen","NAT de: 'früh X' (tracked 'früh aufstehen')"),
("morgens aufwachen","NAT de: 'morgens X'"),
("wecker zum aufstehen","COMP de: 'Wecker zum Aufstehen: Rizen','Ryse - Wecker zum Aufstehen'"),
("leichtes aufstehen","COMP de: 'Wecker für leichtes Aufstehen'"),
("morgens aufstehen","NAT de: 'morgens X'"),
("lichtwecker sonnenaufgang","COMP de: 'Lichtwecker: Sonnenaufgang'"),
("wecker mit sonnenaufgang","NAT de: 'wecker mit X'"),
("sonnenaufgang simulation","NAT de: sunrise-simulation intent (EXT token 'simulator' 63 seed sunrise alarm clock)"),
("sonnenaufgang licht","NAT de: 'sonnenaufgang + licht'"),
("morgenlicht","COMP de: 'Lichtwecker: Sonnenaufgang | Sanft aufwachen im Morgenlicht'"),
("lichtwecker app","NAT de: 'X app'"),
("licht aufwachen","NAT de: 'licht + aufwachen'"),
("aufwachen mit licht","NAT de: 'aufwachen mit X'"),
("sanft wecken","NAT de: 'sanft + wecken'"),
("sanfter alarm","NAT de: 'sanfter X'"),
("wecker sanft","NAT de: word-order variant 'wecker sanft'"),
("sehr lauter wecker","NAT de: 'sehr lauter X'"),
("schlaftracker wecker","COMP de: 'Sleepzy - Schlaftracker-Wecker', 'Wecker ۬ | Schlaftracker & Wecker'"),
("schlaf zyklus","COMP de: 'Sleep Time+: Schlaf Zyklus'"),
("schlafphasen","NAT de: feature term (schlafphasenwecker tracked)"),
("alarm clock for heavy sleepers","NAT de: English query in DE store (en-GB fields)"),
("heavy sleeper alarm","NAT de: English query in DE store"),
("mission alarm","COMP de: 'Mission Alarm: Lauter Wecker'"),
("sunrise simulator","EXT de: token 'simulator'(63) seed 'sunrise alarm clock'"),
("gentle alarm","COMP de: Wonderwake subtitle 'Sunrise Gentle Alarm Clock'"),
("wake up alarm","NAT de: English query in DE store"),
]
