# (term, source)  -- sources: SUG=get_keyword_suggestions(app,store) 2026-09-27; EXT=extract_competitors_keywords(seed); COMP=competitor name/subtitle n-gram; NAT=natural-query pattern
US = [
# suggestions containing core words
("mathe alarm","SUG us: suggestion 'mathe alarm' (pop6) - Mathe Alarm Clock brand variant"),
("mathe alarm clock","SUG us: suggestion 'mathe alarm clock'"),
("sunrise sleep","SUG us: suggestion 'sunrise sleep'"),
("i cant wake up","SUG us: suggestion 'i cant wake up'"),
("sunrise app","SUG us: suggestion 'sunrise app'"),
("my sunrise","SUG us: suggestion 'my sunrise'"),
("wakeup","SUG us: suggestion 'wakeup'"),
("waking up","SUG us: suggestion 'waking up'"),
# competitor extraction (multi-word, contain core word)
("sleep alarm","EXT us: seeds 'loud alarm clock','alarm clock for heavy sleepers'"),
("alarm music","EXT us: seeds 'alarm clock','wake up alarm clock'"),
("music alarm","EXT us: seeds 'alarm clock','wake up alarm clock'"),
("alarm puzzle","EXT us: seeds 'math alarm clock','puzzle alarm clock'"),
("math puzzle","EXT us: seed 'math alarm clock'"),
("alarm mathe","EXT us: seeds 'math alarm clock','puzzle alarm clock'"),
("fast math","EXT us: seed 'heavy sleepers'"),
("barcode alarm","EXT us: seeds 'alarm clock for heavy sleepers','puzzle alarm clock'"),
("custom alarm","EXT us: seed 'alarm sounds'"),
("alarm app","EXT us: seeds 'puzzle alarm clock','morning alarm'"),
("clock app","EXT us: seeds 'puzzle alarm clock','morning alarm'"),
("clock alarm","EXT us: seeds 'alarm clock','heavy sleepers'"),
("iphone clock","EXT us: seed 'alarm sounds'"),
("night clock","EXT us: seed 'sunrise lamp'"),
("sunrise sunset","EXT us: seed 'sunrise lamp'"),
("challenge tracker","EXT us: seed 'no snooze'"),
("sleep monitor","EXT us: seeds 'morning alarm','wake up light'"),
("sleep timer","EXT us: seeds 'alarm clock','loud alarm clock'"),
("sleep music","EXT us: seeds 'alarm clock','loud alarm clock'"),
("sleep time","EXT us: seed 'sleep cycle alarm'"),
("cycle tracker","EXT us: seeds 'sleep tracker','sleep cycle alarm'"),
("snore tracker","EXT us: seeds 'mission alarm clock','sleep tracker'"),
("smart recorder","EXT us: seed 'sleep cycle alarm'"),
("max volume","EXT us: seeds 'alarm clock','loud alarm clock' (Loud Alarm Clock subtitle 'Max volume')"),
("loud music","EXT us: seed 'alarm clock'"),
("screen light","EXT us: seed 'sunrise lamp'"),
("night light","EXT us: seed 'sunrise lamp'"),
("led lamp","EXT us: seed 'sunrise lamp'"),
("siren sounds","EXT us: seed 'alarm sounds'"),
# competitor names/subtitles n-grams
("wake up gently","COMP us: 'Clock - Wake Up Gently' (NeonApps) name"),
("alarm clock hd","COMP us: 'Alarm Clock HD' (Impala) name"),
("loud alarms","COMP us: 'Alarm Clock HD' subtitle 'Loud Alarms, Music & Sounds'"),
("alarm clock for me","COMP us: 'Alarm Clock for Me - Wake Up!' name"),
("one touch alarm clock","COMP us: 'One Touch Alarm Clock' name"),
("wake up music","COMP us: 'Alarm Clock - Wake up Music' name"),
("morning music","COMP us: 'Alarm Clock for Me' subtitle 'Sleep Timer & Morning Music'"),
("loudest alarm","COMP us: 'Loud Alarm Clock – the LOUDEST' name"),
("wake up heavy sleepers","COMP us: SuperAlarm subtitle 'Wake Up Heavy Sleepers, Snooze'"),
("alarm for heavy sleepers","COMP us: 'Alarm for Heavy Sleepers: Loud' name"),
("loudest alarm clock app","COMP us: 'Loud Alarm Clock LOUDEST Sleep' name + NAT 'X app'"),
("annoying alarm","COMP us: subtitle 'Loudest ANNOYING Alarm Clock +'"),
("annoying alarm clock","COMP us: subtitle 'Loudest ANNOYING Alarm Clock +'"),
("alarm with tasks","COMP us: 'Alarm Clock ◎' subtitle 'Alarm with 250+ Sounds & Tasks'"),
("wake up fast","COMP us: subtitle 'Math Wake Up Fast Clock Alarms'"),
("wide awake","COMP us: Mathe subtitle 'Instantly Wide Awake' / Light Alarm 'wide awake'"),
("glow alarm","COMP us: 'Glow Alarm - Wake Up Light' name"),
("wake up at sunrise","COMP us: 'Sunrise Alarm Clock -' subtitle 'Wake up at sunrise'"),
("sunrise alarm lite","COMP us: 'Dawn - Sunrise Alarm Lite' name"),
("light based alarm","COMP us: Dawn subtitle 'Gentle light-based alarm clock'"),
("gentle sunrise alarm","COMP us: WakeRight subtitle 'Gentle Sunrise Alarm Clock'"),
("dawn simulation","COMP us: 'Wake Up Light – Sunrise Alarm' subtitle 'Simulate Dawn Sunlight'"),
("wake up clock","COMP us: Sleepwave subtitle 'Sleep Monitor & Wake Up Clock'"),
("sunrise alarm clock sounds","COMP us: 'Sunrise Alarm Clock & Sounds' name"),
("wake up refreshed","COMP us: 'Sunrise Clock: Loud Alarm' subtitle 'WakeUp Refreshed Every Morning'"),
# natural patterns (en)
("alarm clock app","NAT us: 'X app'"),
("best alarm clock","NAT us: 'best X'"),
("best alarm app","NAT us: 'best X'"),
("free alarm clock","NAT us: 'free X'"),
("alarm clock free","NAT us: 'X free'"),
("alarm for deep sleepers","NAT us: 'alarm for <user>' (deep sleeper synonym of heavy sleeper)"),
("deep sleeper alarm","NAT us: synonym of 'heavy sleeper alarm'"),
("heavy sleeper alarm clock","NAT us: 'heavy sleeper' + head"),
("alarm clock heavy sleeper","NAT us: word-order variant"),
("alarm that wont turn off","NAT us: problem query"),
("alarm clock with math","NAT us: 'X with <feature>'"),
("alarm with math problems","NAT us: 'X with <feature>'"),
("math problem alarm","NAT us: feature + head"),
("math alarm app","NAT us: 'X app'"),
("puzzle alarm app","NAT us: 'X app'"),
("alarm with puzzles","NAT us: 'X with <feature>'"),
("mission alarm app","NAT us: 'X app'"),
("alarm missions","NAT us: head + feature"),
("wake up missions","NAT us: wake + feature"),
("no snooze alarm","NAT us: feature + head"),
("anti snooze alarm","NAT us: feature + head"),
("alarm without snooze","NAT us: 'X without <feature>'"),
("snooze proof alarm","NAT us: from 'snoozeproof' (EXT us seed 'no snooze')"),
("loud alarm app","NAT us: 'X app'"),
("extra loud alarm","NAT us: intensifier + head"),
("very loud alarm","NAT us: intensifier + head"),
("super loud alarm clock","NAT us: intensifier + head"),
("loud wake up alarm","NAT us: loud + wake up alarm"),
("sunrise alarm app","NAT us: 'X app'"),
("sunrise light alarm","NAT us: sunrise + light alarm"),
("sunrise wake up light","NAT us: sunrise + wake up light"),
("sunrise simulation","NAT us: sunrise + simulation (cf 'dawn simulator' tracked)"),
("sunrise alarm free","NAT us: 'X free'"),
("sun alarm","NAT us: field token 'sun' + alarm"),
("sunlight alarm","NAT us: from EXT us 'sunlight' (seeds 'wake up light','sunrise lamp') + alarm"),
("dawn alarm clock","NAT us: field 'dawn' + head"),
("light alarm clock","NAT us: 'light alarm' + clock"),
("alarm clock with light","NAT us: 'X with <feature>'"),
("wake up app","NAT us: 'X app'"),
("wake up early alarm","NAT us: goal + head"),
("wake up challenge","NAT us: wake + challenge"),
("wake me up","NAT us: natural phrase"),
("wake up call","NAT us: natural phrase"),
("help me wake up","NAT us: natural phrase"),
("gentle wake up alarm","NAT us: subtitle 'gentle' + wake up alarm"),
("smart wake up","NAT us: field 'smart' + wake up"),
("smart wake up alarm","NAT us: field 'smart' + wake up alarm"),
("morning alarm clock","NAT us: morning + head"),
("morning wake up","NAT us: morning + wake up"),
("good morning alarm","NAT us: natural phrase"),
("morning routine alarm","NAT us: field 'morning routine' + alarm"),
("alarm challenge","NAT us: head + challenge"),
("alarm clock challenge","NAT us: head + challenge"),
("challenge alarm clock","NAT us: challenge + head"),
("alarm with challenges","NAT us: 'X with <feature>' (EXT us 'challenges' seeds puzzle/mission)"),
("shake alarm","NAT us: feature + head (EXT us 'shake' seed 'alarm clock for heavy sleepers')"),
("shake alarm clock","NAT us: feature + head"),
("shake to stop alarm","NAT us: natural phrase"),
("sleep cycle alarm clock","NAT us: field tokens 'sleep','cycle' + head"),
("sleep tracker alarm","NAT us: field tokens + alarm"),
("sleep tracker and alarm","NAT us: field tokens + alarm"),
("alarm sounds loud","NAT us: field 'sounds','loud'"),
("loud alarm clock for heavy sleepers","NAT us: loud + 'alarm clock for heavy sleepers'"),
]
BR = [
("despertador iphone","SUG br: suggestion 'despertador iphone'"),
("relogio digital","SUG br: suggestion 'relógio digital' (field 'relogio')"),
("despertador com desafios","NAT br + EXT br token 'desafios' (competitor extraction)"),
("despertador com desafio","NAT br: 'despertador com <feature>'"),
("alarme com desafio","NAT br: 'alarme com <feature>'"),
("alarme desafio","NAT br: head + feature"),
("despertador desafio","NAT br: head + feature"),
("despertador com jogo","NAT br: 'despertador com <feature>' (EXT br 'jogos')"),
("despertador com conta","NAT br + EXT br token 'conta'"),
("alarme com conta","NAT br + EXT br token 'conta'"),
("despertador matematico","NAT br: adjective form of matematica"),
("alarme matematico","NAT br: adjective form of matematica"),
("despertador com matematica","NAT br: 'despertador com <feature>'"),
("alarme com matematica","NAT br: 'alarme com <feature>'"),
("despertador com missao para acordar","COMP br: 'Despertador - SmartClock' subtitle 'Alarme com missão para acordar'"),
("alarme com missao para acordar","COMP br: SmartClock subtitle 'Alarme com missão para acordar'"),
("despertador com missao diaria","COMP br: 'Kairo' subtitle 'Despertador com missão diária'"),
("despertador sem soneca","COMP br: 'KUKO: Despertador sem Soneca' (already tracked)"),
("alarme sem soneca","NAT br: 'alarme sem <x>' (KUKO name)"),
("chega de soneca","COMP br: ByeBed subtitle 'Chega de snooze' localized"),
("alarme para sono pesado","NAT br: 'alarme para <user>'"),
("sono pesado","NAT br: core phrase alone"),
("despertador para quem tem sono pesado","NAT br: natural long query"),
("despertador para dorminhoco","NAT br: 'para <user>' (field 'dorminhoco')"),
("alarme para dorminhoco","NAT br: 'para <user>'"),
("despertador que nao desliga","NAT br: problem query"),
("despertador muito alto","NAT br: intensifier + field 'alto'"),
("despertador muito forte","NAT br: intensifier + field 'forte'"),
("alarme muito alto","NAT br: intensifier"),
("alarme muito forte","NAT br: intensifier"),
("despertador barulhento","NAT br: synonym of alto"),
("alarme barulhento","NAT br: synonym of alto"),
("som de despertador","NAT br: 'som de X'"),
("som de alarme","NAT br: 'som de X' (EXT br 'sons','toques')"),
("toque de despertador","NAT br: 'toque de X' (EXT br 'toques')"),
("sons de alarme","NAT br + EXT br 'sons'"),
("alarmes altos","COMP br: 'Despertador: Alarmes Altos ◎' name"),
("alarme com 250 sons","COMP br: RV subtitle 'Alarme com 250+ Sons e Tarefas'"),
("alarme com tarefas","COMP br: RV subtitle 'Sons e Tarefas' + EXT br 'tarefas'"),
("despertador gratis","NAT br: 'X gratis'"),
("alarme gratis","NAT br: 'X gratis'"),
("app despertador","NAT br: 'app de X'"),
("app de despertador","NAT br: 'app de X'"),
("app alarme","NAT br: 'app X'"),
("app para acordar","NAT br: 'app para <objetivo>'"),
("app para acordar cedo","NAT br: 'app para <objetivo>'"),
("alarme para acordar","NAT br: 'alarme para <objetivo>'"),
("alarme para acordar cedo","NAT br: 'alarme para <objetivo>'"),
("acordar com luz","NAT br: acordar + field 'luz'"),
("acordar de manha","NAT br: acordar + field 'manha'"),
("acordar no horario","NAT br: natural phrase"),
("acordar disposto","COMP br: Wayk/competitor copy + NAT"),
("pare de adiar o despertador","COMP br: Wayk subtitle 'Pare de adiar, acorde cedo'"),
("acorde cedo","COMP br: Wayk subtitle 'acorde cedo' (imperative)"),
("despertador de luz","NAT br: 'despertador de <x>' (field 'luz')"),
("alarme com luz","NAT br: 'alarme com <x>'"),
("despertador luz do sol","NAT br: luz + EXT br 'sol'"),
("despertador nascer do sol","NAT br: tracked 'nascer do sol' + head"),
("alarme nascer do sol","NAT br: 'nascer do sol' + alarme"),
("luz do amanhecer","NAT br: luz + amanhecer"),
("alarme amanhecer","NAT br: alarme + field 'amanhecer'"),
("despertador sunrise","NAT br: head + EN 'sunrise' (name token)"),
("alarme inteligente","NAT br: synonym 'despertador inteligente' (tracked)"),
("alarme dificil","NAT br: synonym 'despertador dificil' (tracked)"),
("relogio despertador alto","NAT br: tracked 'relogio despertador' + field 'alto'"),
("relogio alarme","NAT br: field tokens"),
("relogio despertador gratis","NAT br: 'X gratis'"),
("despertador de manha","NAT br: head + field 'manha'"),
("alarme ciclo do sono","NAT br: alarme + tracked 'ciclo do sono'"),
("despertador ciclo do sono","NAT br: head + 'ciclo do sono'"),
("despertador chacoalhar","NAT br: shake feature (chacoalhar)"),
("alarme sacudir celular","NAT br: shake feature"),
("rotina matinal","NAT br + EXT br 'rotina' (seed despertador/alarme)"),
("despertador rotina","NAT br: EXT br 'rotina' + head"),
# EN in BR (LEARNINGS #36)
("loud alarm clock","SUG es: 'loud alarm clock' pop40 in es -> EN query checked in BR (LEARNINGS #36)"),
("alarm clock for heavy sleepers","NAT: EN head query checked in BR (LEARNINGS #36)"),
("math alarm clock","NAT: EN query checked in BR"),
("wake up alarm","NAT: EN query checked in BR"),
("smart alarm clock","NAT: EN query checked in BR"),
]
ES = [
("alarma matemática","SUG es: suggestion 'alarma matemática'"),
("alarma con matemáticas","SUG es: suggestion 'alarma con matemáticas'"),
("alarma matematica","SUG es: suggestion 'alarma matematica'"),
("loud alarm clock","SUG es: suggestion 'loud alarm clock' (EN query in es)"),
("reloj alarma","EXT es: token pair 'reloj alarma' (seed despertador/alarma)"),
("sueño seguimiento","EXT es: 'sueño seguimiento'"),
("despertador con retos","NAT es + EXT es token 'retos'"),
("alarma con retos","NAT es + EXT es token 'retos'"),
("despertador con reto","NAT es: 'despertador con <feature>'"),
("alarma con reto","NAT es: 'alarma con <feature>'"),
("despertador con juegos","NAT es + EXT es 'juegos'"),
("alarma con juegos","NAT es + EXT es 'juegos'"),
("despertador con puzles","NAT es + EXT es 'puzles'"),
("alarma con puzzles","NAT es + field-era token 'puzzle'"),
("despertador con matematicas","NAT es: 'despertador con <feature>'"),
("despertador matematico","NAT es: adjective form"),
("despertador con tareas","NAT es + EXT es 'tarea' (RV subtitle 'Alarma con 250 sonidos y tarea')"),
("alarma con 250 sonidos","COMP es: 'Despertador: Alarmas Fuertes ◎' subtitle"),
("alarmas fuertes despertador","COMP es: 'Despertador: Alarmas Fuertes ◎' name"),
("alarma fuerte y reloj","COMP es: 'Alarmy - Alarma Fuerte y Reloj' name"),
("despertador inteligente alarma","COMP es: 'Alarma | Despertador Inteligente'"),
("reloj despertador inteligente","COMP es: 'Alarma despertador con música.' subtitle 'Reloj despertador inteligente'"),
("despertar al instante","COMP es: 'Mathe Alarm Clock -Despertador' subtitle"),
("levantate ya","COMP es: Wayk subtitle 'No más snooze, levántate ya'"),
("adios al snooze","COMP es: Wayk subtitle 'Adiós al snooze'"),
("despertador sin posponer","NAT es: 'despertador sin <x>' (tracked 'despertar sin posponer')"),
("alarma sin posponer","NAT es: 'alarma sin <x>'"),
("alarma sin snooze","NAT es: 'alarma sin <x>'"),
("despertador para dormilones","NAT es: 'para <user>' (field 'dormilon')"),
("alarma para dormilones","NAT es: 'para <user>'"),
("despertador para sueño pesado","NAT es: 'para <user>'"),
("alarma para sueño pesado","NAT es: 'para <user>'"),
("sueño pesado","NAT es: core phrase alone"),
("despertador muy fuerte","NAT es: intensifier"),
("alarma muy fuerte","NAT es: intensifier"),
("despertador ruidoso","NAT es: synonym of fuerte"),
("alarma ruidosa","NAT es: synonym of fuerte"),
("sonido de alarma fuerte","NAT es: 'sonido de X'"),
("sonidos de alarma","NAT es + EXT es 'sonidos'"),
("tonos de alarma","NAT es + EXT mx 'tonos'"),
("despertador gratis","NAT es: 'X gratis'"),
("alarma gratis","NAT es: 'X gratis'"),
("app despertador","NAT es: 'app X'"),
("app alarma","NAT es: 'app X'"),
("app para despertar","NAT es: 'app para <objetivo>'"),
("alarma para despertar","NAT es: 'alarma para <objetivo>'"),
("alarma para despertar temprano","NAT es: 'alarma para <objetivo>'"),
("despertador para levantarse","NAT es: 'para <objetivo>' (tracked 'levantarse de la cama')"),
("alarma para levantarse","NAT es: 'para <objetivo>'"),
("despertar con luz","NAT es: despertar + field 'luz'"),
("despertar suave","NAT es: despertar + field 'suave'"),
("despertador de luz","NAT es: 'despertador de <x>'"),
("alarma de luz","NAT es: 'alarma de <x>'"),
("luz de amanecer","NAT es: luz + amanecer"),
("despertador sol","NAT es: head + sol"),
("despertador salida del sol","NAT es: sunrise = 'salida del sol'"),
("alarma salida del sol","NAT es: sunrise = 'salida del sol'"),
("despertador sunrise","NAT es: head + EN name token"),
("alarma de la mañana","NAT es: field 'manana'"),
("alarma mañana","NAT es: field 'manana'"),
("despertador ciclo de sueño","NAT es: head + tracked 'ciclo de sueño'"),
("alarma ciclo de sueño","NAT es: alarma + 'ciclo de sueño'"),
("despertador agitar","NAT es: shake feature (agitar)"),
("alarma agitar telefono","NAT es: shake feature"),
("reloj despertador con luz","NAT es: tracked 'reloj despertador' + 'con luz'"),
("reloj despertador gratis","NAT es: 'X gratis'"),
("alarma temprano","NAT es: alarma + field 'temprano'"),
("despertador temprano","NAT es: head + field 'temprano'"),
("rutina de mañana","NAT es: morning routine"),
("alarm clock for heavy sleepers","NAT: EN head query checked in es/mx (LEARNINGS #36)"),
("math alarm clock","NAT: EN query checked in es/mx"),
("wake up alarm","NAT: EN query checked in es/mx"),
]
MX_EXTRA = [
("alarma para despertarse","NAT mx: reflexive 'despertarse' (MX usage)"),
("despertador que no se apague","NAT mx: problem query"),
("alarma con misiones para despertar","COMP mx: Wayk 'Despertador con Misión' + NAT 'para <objetivo>'"),
("alarma sonido fuerte","NAT mx: word order variant"),
]
